export const LOGO_URL = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoLI_uxIDAxCCK46tTEBxgIbto8Znd9-GBfQ&s"
export const REST_IMG_URL = "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/"
export const DATA_API_URL = "https://www.swiggy.com/dapi/restaurants/list/v5?lat=18.5483103&lng=73.791107&is-seo-homepage-enabled=true&page_type=DESKTOP_WEB_LISTING"
export const REST_MENU_API_URL = "https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=18.5642452&lng=73.7768511&restaurantId="
export const FAQs_API_URL = "https://www.swiggy.com/dapi/support/v3/issues/faq"